name: build-resume
on:
  push:
    branches:
      - 'master'
      - 'feature/*'
    paths: 
      - '**.tex'
      - '**.cls'
      - '!Dockerfile'
      - '.github/workflows/build-resume.yml'

jobs:
  build_resume:
    runs-on: ubuntu-latest
    container:
      image: dtourde/build-awesomecv-resume:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: inject secret vars into container
        run: |
          echo '${{ secrets.MAIL }}' > mail.tex && \
          echo '${{ secrets.MICHEL }}' > michel.tex && \
          echo '${{ secrets.PHONE }}' > phone.tex 

      - name: build with Xelatex
        run: |
          xelatex julienchampenois.tex

      - uses: "marvinpinto/action-automatic-releases@latest"
        name: "push resume on Github release - latest"
        if: "contains(github.event.ref, 'refs/heads/master')"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Resume"
          files: |
            julienchampenois.pdf
      
      - uses: "marvinpinto/action-automatic-releases@latest"
        name: "push resume on Github release - feature"
        if: "contains(github.event.ref, 'feature')"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "draft"
          draft: true
          title: "Resume"
          files: |
            julienchampenois.pdf
