name: build-resume
on:
  push:
    branches:
      - 'master'
      - 'feature/*'
    paths: 
      - '**.tex'
      - '**.cls'
      - '!Dockerfile'

jobs:
  build_resume:
    runs-on: ubuntu-latest
    container:
      image: dtourde/build-awesomecv-resume:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: |
          echo '${{ secrets.MAIL }}' > mail.tex && \
          echo '${{ secrets.ADDRESS }}' > address.tex && \
          echo '${{ secrets.PHONE }}' > phone.tex

      - name: build with Xelatex
        run: |
          xelatex damientourde.tex

      - uses: "marvinpinto/action-automatic-releases@latest"
        name: "push resume on Github release"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Resume"
          files: |
            damientourde.pdf